name: Swift Tests
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'NTP.podspec'
      - 'README.md'
      - 'LICENSE'
      - 'swift-generate-documentation.sh'
      - 'docs/**'
      - '.spy.yml'
      - '.gitignore'
  pull_request:
    branches: 
      - '*'
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  tests:
    name: Swift ${{ matrix.swift }} on ${{ matrix.platform }}
    strategy:
      matrix:
        platform: ['macOS', 'iOS']
        swift: ["5.9", "6.0"]
    runs-on: macos-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Run swift tests
        run: swift test
